// acTIONS FOR AN API CALL
export const POST_API_STARTED = "POST_API_STARTED"; //CONTROLS LOADING STATUS FOR API
export const POST_API_SUCCESS = "POST_API_SUCCESS";
export const POST_API_FAILURE = "POST_API_FAILURE";